version: "3"

x-var: &base
  env_file:
    - .env

services:
  db:
    container_name: mongo_db
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db:/data/db

  backend:
    <<: *base
    tty: true
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    ports:
      - 3000:8080
    volumes:
      - ./packages/backend:/app
    command: npm run start:dev
    depends_on:
      - db

  frontend:
    <<: *base
    tty: true
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    ports:
      - 8000:3000
    volumes:
      - ./packages/frontend:/app
    command: npm run dev
    depends_on:
      - backend
